---
# tasks file for minishift

  - name: install required rpms
    dnf:
      state: latest
      name: "{{ item }}"
    loop:
      - libvirt
      - qemu-kvm
      - origin-clients
      - libselinux-python
  
  - name: start and enable libvirtd
    system:
      name: libvirtd
      enabled: yes
      state: started

  - name: create "{{ minishift_user }}" and add to the libvirt group
    user:
      name: "{{ minishift_user }}"
      comment: The person using minishift
      groups: "{{ minishift_group }}"

  - name: download minishift
    get_url:
      url: "{{ minishift_url }}"
      dest: "{{ minishift_tmp }}"

  - name: unarchive minishift
    unarchive:
      src: "{{ minishift_tmp }}/{{ minishift_version }}"
      dest: /usr/local/bin
      remote_src: yes
      creates: "/usr/local/bin/{{ minishift_version }}"
      mode: 755

  - name: move the binary from the tar output
    copy:
      src: /usr/local/bin/{{ minishift_binary_copy}}/{{ minishift_binary }}
      dest: /usr/local/bin/{{ minishift_binary }}
      remote_src: yes
