---
# tasks file for minishift

  - include_tasks: centos.yml
    when: ansible_pkg_mgr == "yum" and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" )

  - name: install required rpms
    yum:
      state: latest
      name: "{{ minishift_rpms }}"
    notify: start and enable libvirtd

  - name: create "{{ minishift_user }}" and add to the libvirt group
    user:
      name: "{{ minishift_user }}"
      comment: The person using minishift
      groups: "{{ minishift_group }}"

  - name: download the kvm file used to be able to run minishift
    get_url:
      url: "{{ minishift_kvm }}"
      dest: "{{ minishift_dir }}"
      
  - name: download minishift
    get_url:
      url: "{{ minishift_url }}"
      dest: "{{ minishift_tmp }}"
      validate_certs: no

  - name: unarchive minishift
    unarchive:
      src: "{{ minishift_tmp }}/{{ minishift_version }}"
      dest: /usr/local/bin
      remote_src: yes
      creates: "/usr/local/bin/{{ minishift_version }}"
      mode: 755

  - name: move the binary from the tar output
    copy:
      src: /usr/local/bin/{{ minishift_binary_copy}}/{{ minishift_binary }}
      dest: /usr/local/bin/{{ minishift_binary }}
      remote_src: yes
